### ISSUE TITLE
Backup Camera resets if ACC control is used on the PowerSwitch

### ISSUE THREAD

**Issue by sob** [sob/shopmanual.io#2]
The backup camera reboots if the key moves from ACC to RUN. 

**To Reproduce**
1. Configure the PowerSwitch to allow the ACC control input to manage the rear camera
2. With vehicle off, use the remote start to turn on the vehicle
3. Camera should boot normally
4. Use the key to turn the vehicle from OFF -> ON
5. Camera reboots

**Expected behavior**
Camera should stay on from remote start -> key on position

**Additional context**
@jon-dutch take:

> For the backup camera system, I know ours runs either an internal battery or a capacitor pack, to maintain power when the key switches from ACC to Start.

**Comment by jon-dutch** [comment]
This camera system is aftermarket, right?

**Comment by sob** [comment]
Yep!: [Auto-Vox V5Pro](https://www.amazon.com/gp/product/B0895NMDKT/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1)

**Comment by jon-dutch** [comment]
I'm thinking a timer relay is your best option here. You could either apply it to just the camera system, or to the whole array of circuits that need an ACC signal. So use the cars ACC to feed the timer, and then use the timer output to switch the Garmin. That way the Garmin will maintain a connection when switching, unless the timer elapses. Even a 10s timer would work.

**Comment by sob** [comment]
I need to repeat the validation of this. The behavior isn't always consistent. One thing I have noticed is the PowerSwitch appears to work turning this on, but when ACC loses power it doesn't turn off. I think the issue is either the ACC tap, or the input from the PowerSwitch is a momentary input. That's not configurable in the app so I suppose I can open a ticket with Garmin (they don't do phone support for PowerSwitch).

**Comment by jon-dutch** [comment]
Have you gone through the camera menu to see if there are settings that may control the delay?

**Comment by sob** [comment]
Checked the camera menu, nothing there. I have validated that the ACC control is working for turn on, but need to validate that it is in fact turning off the device once I leave the vehicle. My concern is that the ACC control works for turn on, but not necessarily for turn off at this point.

Keeping this open for now.

**Comment by sob** [comment]
Second time since PowerSwitch install that the battery is dead and vehicle won't start. Van sat since Saturday night and was dead by Monday morning. Need to jump and then verify the settings for the mirror. My hunch is that the mirror is not turning off. That the ACC control for the PowerSwitch will work for power on, but will not work for power off.

Presents an interesting problem with the reverse light scenario. One of my plans was to tie in the reverse light function into the second PowerSwitch to turn on rock lights or some other lights on the curb side of the vehicle because it's difficult to parallel park in the dark. If putting the vehicle in reverse works to turn on the lights, but then a manual turn off that would defeat the purpose of these things entirely.

**Comment by jon-dutch** [comment]
Have you verified that the ACC circuit is indeed losing power and going to zero vdc? Is this a real ACC connection, or still running through the lamp? 

I still think you should have a primary relay between the battery and PowerSwitch to be able to completely break that link when parked up.

Can you try just using a toggle switch with a 12v source to simulate the ACC on-off functionality to see if it is indeed an "on-only" scenario? My guess right now is that there may actually be some voltage floating around on that ACC line, even when off - possibly via a backfeed - and the PS sees it as still active but other devices have a higher cutoff limit so they are working correctly.

**Comment by sob** [comment]
That's a good idea:

1. I'll wire a rocker switch inline to the ACC feed that is coming from the lamp to validate the on-only scenario
2. If test passes (switch kills power, devices turn off) then I'll pull a new ACC connection from someplace else using the wiring diagram

I'll determine timer relay and/or kill switch based on findings above.

**Comment by sob** [comment]
It suddenly dawned on me while driving down the road this morning, but it's not an ACC pole that I did. The overhead lights can be turned on without the key in the ignition. The reason the screens were tapped into that, is because they have a similar light that can be turned on without the key, and that is activated by the door.

I need to run a new ACC line.

**Comment by sob** [comment]
So this realization above turned out to be correct. What I thought was the ignition line was actually just a 12v battery connection through the power distribution center. I ran a new wire but then accidentally tapped into the reverse by misreading the wiring diagram. So I ran a second wire from the ACC. I now have to control inputs on the first PowerSwitch, one for reverse and one for ACC.

I've configured the mirror to turn off with the ACC connection and will configure each device to turn "off" but not on when the input is toggled.

I do wish you could rename input controls on the PowerSwitch to keep things clear in the app.

**Comment by jon-dutch** [comment]
Well shit! Glad to hear it. Congrats on the win!
